### PR TITLE
table-practice

### PR DESCRIPTION
**Pull request by eddieharmon**

### CODE REVIEW

**Comment by eddieharmon** [comment]
@bontgoy

**Comment by Bontgoy** [comment]
@eddieharmon do you have any questions about this file?  You don't need to tag me in PRs if you don't have questions.

**Comment by Bontgoy** [comment]
@eddieharmon  This table looks good! Do you have any questions about the file or submission that you would like me to answer specifically?

**Comment by eddieharmon** [comment]
Sorry @Bontgoy , I was still learning how and if the tagging feature would work, so I was testing the feature out. I don't have any questions on it so far, but I'm sure there are more to come!

**Pull request merged**
